### ISSUE TITLE
训练自己的数据？

### ISSUE THREAD

**Issue by ZDstandup** [INVOKERer/AdaRevD#18]
您好，请问您的代码 可以用来从头训练自己的数据集吗？是否必须要使用预训练的模型？

**Comment by INVOKERer** [comment]
我这个模型的初衷是以小的训练代价提升现有模型的解码能力。当然，也可以尝试更改编码器后end2end地从头训练自己的数据集。

**Comment by ZDstandup** [comment]
好的 谢谢
