### ISSUE TITLE
Help for data preparation

### ISSUE THREAD

**Issue by David-Morales-Norato** [INVOKERer/AdaRevD#19]
Dear Authors,

Thank you for making this repository available; it's been incredibly helpful for my work.

I am interested in fine-tuning your models on a different dataset but am encountering some difficulties with the data preparation process. Could you please provide a detailed explanation or guidance on how to correctly prepare the dataset for fine-tuning?

Here are the steps I've taken so far:

1. Ran Motion_Deblurring/download_data.py
2. Executed scripts/data_preparation/gopro.py

Despite these attempts, I'm unsure if I'm following the correct procedure, be cause I had modified manually some parts of the code to make it work. I really would appreciate any assistance you can offer.

Thank you for your time and help.

Best regards,

**Comment by INVOKERer** [comment]
Hi, maybe you can get it from [Restormer](https://github.com/swz30/Restormer/tree/main/Motion_Deblurring).
