### ISSUE TITLE
关于Adaptive训练部分

### ISSUE THREAD

**Issue by chuanshuojibi** [INVOKERer/AdaRevD#24]
readme中并未提到这部分训练办法，而按照配置文件模板进行的一直报错loss的计算不对，按我理解的encoder使用ufpnet和decoder使用pretrain然后添加classifier，最终报错是模型权重缺失，希望能够解惑

**Comment by INVOKERer** [comment]
你好，你使用的是GoPro-AdaRevIDB-classify-4gpu.yml？我在readme中的Training部分有简单说明这个训练方式。

**Comment by chuanshuojibi** [comment]
> 你好，你使用的是GoPro-AdaRevIDB-classify-4gpu.yml？我在readme中的Training部分有简单说明这个训练方式。

感谢回复，我使用的是GoPro-AdaRevIDB-Adaptive-4gpu.yml 所以这个东西并不需要存在吗？

**Comment by chuanshuojibi** [comment]
> 抱歉，当时我把很多ablation等其他实验用的yml也一起上传了。

好吧我错误理解有三次训练的，感谢回复。
