### ISSUE TITLE
classifier怎么运用到AdaRev中

### ISSUE THREAD

**Issue by dreamitposssiable** [INVOKERer/AdaRevD#33]
作者您好，我在读代码的时候发现AdaRevIDSlide的classifier_type设置的是single，有些困惑论文中的分类器结果怎么运用到AdaRev中

**Comment by INVOKERer** [comment]
你好，具体的参数是由Options/AdaRevID-B-GoPro-test.yml中的classifier_type指定。

**Comment by dreamitposssiable** [comment]
不好意思哈，我的问题可能有点多，我很困惑，是需要先将模糊图像分类，然后根据分类结果手动更改参数然后分别测试吗？如果想根据classier对模糊图像进行AdaRevID训练应该怎么操作，是只运行GoPro-AdaRevIDB-classify-4gpu.yml就可以了吗，需不需要运行AdaRevID的yml？文件名含test的文件，里面有train的配置，test文件是包含训练的文件吗？六个补丁类是通过文件GoPro-AdaRevIDB-classify-4gpu.yml进行分类的吗，为什么GoPro-AdaRevIDB-classify-4gpu.yml参数里直接写的hard_simple？

**Comment by INVOKERer** [comment]
1. 是根据分类器的结果手动调整不同类别在不同的decoder退出；
2. GoPro-AdaRevIDB-classify-4gpu.yml只会训练分类器，整体框架和分类器是分别训练的；
3. 测试时只会用到test文件里面模型配置，训练配置我偷懒没删掉；
4. 六个补丁类是通过文件GoPro-AdaRevIDB-classify-4gpu.yml进行训练的，hard_simple是指分类器的方式，即论文中使用的分类方法。

**Comment by dreamitposssiable** [comment]
非常感谢作者的详细回答，我运行GoPro-AdaRevIDB-classify-4gpu.yml后，没有直接显示分别哪些属于6个类别，仅仅是保存了最后的网络结构，我应该怎么去查看它们分别属于六个类别中的哪一类？
我也比较困惑分别训练AdaRevID和classify，AdaRevID就已经出现重建结果了，怎么用classify进行AdaRevID重建？

**Comment by INVOKERer** [comment]
训练是GoPro-AdaRevIDB-classify-4gpu.yml，测试是AdaRevID-B-GoPro-test.yml。

**Comment by dreamitposssiable** [comment]
明白了，感谢回答

**Comment by dreamitposssiable** [comment]
你好，我在运行GoPro-AdaRevIDB-classify-4gpu.yml的时候，损失函数一直显示为0，这个是正常情况吗？
readme中train部分分别训练了AdaRev主体和classifier，是在训练classifier的时候是也运用了AdaRev主体吗？
训练AdaRev主体是为了对比有无classifier的区别吗？因为在运行AdaRev主体的时候发现已经出来重建结果了。
我发现我还是很困惑，为什么分开训练之后不需要合在一起。

**Comment by INVOKERer** [comment]
1. 损失函数一直显示为0是不正常的，应该是有loss的；
2. 训练classifier的时候也运用了AdaRev主体；
3. 训练AdaRev主体是为了提升现有模型的解码能力；
4. 为什么分开训练之后不需要合在一起，是可以直接用GoPro-AdaRevIDB-classify-4gpu.yml训练好后的模型，我只是把他们分开了，为了节约存储空间。

**Comment by dreamitposssiable** [comment]
感谢作者详细的解答
